// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyD7cL39rmwBdhdoZsFhebEUYKQPkqRqnx0',
    appId: '1:611489504374:web:ce9dc2a93957d631751357',
    messagingSenderId: '611489504374',
    projectId: 'meu-virtual-nutri',
    authDomain: 'meu-virtual-nutri.firebaseapp.com',
    storageBucket: 'meu-virtual-nutri.firebasestorage.app',
    measurementId: 'G-M9N2M3KVSM',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCRnMuCHQkIZVoK1bl6YZe9-poaaw9SvHs',
    appId: '1:611489504374:android:4a5a570900b76368751357',
    messagingSenderId: '611489504374',
    projectId: 'meu-virtual-nutri',
    storageBucket: 'meu-virtual-nutri.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyAdvCzLkvEcyn3MUTY8H-FiVfalHjnii3U',
    appId: '1:611489504374:ios:61076d1cfee2e932751357',
    messagingSenderId: '611489504374',
    projectId: 'meu-virtual-nutri',
    storageBucket: 'meu-virtual-nutri.firebasestorage.app',
    iosBundleId: 'com.example.mvnApp',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyAdvCzLkvEcyn3MUTY8H-FiVfalHjnii3U',
    appId: '1:611489504374:ios:61076d1cfee2e932751357',
    messagingSenderId: '611489504374',
    projectId: 'meu-virtual-nutri',
    storageBucket: 'meu-virtual-nutri.firebasestorage.app',
    iosBundleId: 'com.example.mvnApp',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyD7cL39rmwBdhdoZsFhebEUYKQPkqRqnx0',
    appId: '1:611489504374:web:5d202653b0811b5e751357',
    messagingSenderId: '611489504374',
    projectId: 'meu-virtual-nutri',
    authDomain: 'meu-virtual-nutri.firebaseapp.com',
    storageBucket: 'meu-virtual-nutri.firebasestorage.app',
    measurementId: 'G-RXJKS9F276',
  );
}
